### ISSUE TITLE
Domain Variant

### ISSUE THREAD

**Issue by npsumesh** [CodeMakerInc/EppLib.NET#11]
Hello,
How to add domain variant for arabic domains...?

**Comment by ademar** [comment]
Hi,

At the moment the library does not have support for domain name variants. It is my understanding that support for this would need to be added as an EPP extension and that registrars may have different implementations.

Regards,

**Comment by npsumesh** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
 <epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
    <extension>
       <command xmlns="urn:X-ar:params:xml:ns:viext-1.0">
        <variantInfo>
          <variantInfo xmlns="urn:X-ar:params:xml:ns:variant-1.0">
               <name language="gr">δείγμα.idn</name>
           </variantInfo>
        </variantInfo>
       <clTRID>ABC-12345</clTRID>
     </command>
  </extension>
 </epp>

This is the command for domain variant.  How do i create this command?

**Comment by ademar** [comment]
> At the moment the library does not have support for domain name variants.

So unless someone implement the required extension it can not be done.
