### ISSUE TITLE
Nominet Domain Privacy

### ISSUE THREAD

**Issue by luke-dobson** [CodeMakerInc/EppLib.NET#18]
Are there any plans to add Domain Privacy support, we're looking at Nominet specifically.  If not we will probably pick this up ourselves but don't want to start if this is already in progress

**Comment by luke-dobson** [comment]
Found the logic for this, it seems to be incomplete and got at least one bug in it, we're implementing this and will push this back in as soon as we're through QA

**Comment by ademar** [comment]
:+1:

**Comment by luke-dobson** [comment]
Changes complete (live for us) and awaiting pulling back up into master
