### ISSUE TITLE
EPP error: Parameter value range error

### ISSUE THREAD

**Issue by rserit** [CodeMakerInc/EppLib.NET#23]
Hello,
We using EppLib.NET. Our projects about domains (transfer, renew...). It's work, no problem. But when i change our server password (on remote desktop), Epp doesn't work. I don't understand.
`Error:  Parameter value range error Wrong curExpDate provided.`

It doesn't seems like about server password, but when i change server password, it doesn't work.
Is anyone whom i consultant about this problem?

**Comment by ademar** [comment]
The error you mention have nothing to do with authentication.

> Error: Parameter value range error Wrong curExpDate provided.

I have seen this error when you try to renew a domain and you send an invalid date or the `curExpDate` you are sending does not match the date in the registry. 

Note that if you are registering .CA through CIRA they auto-renew domains and often the `curExpDate` in your database does not match the one in the registry.

By the way, can we know which domain registry are you using ?

**Comment by rserit** [comment]
@ademar thank you for reply. 
I take a photo about this error. It's [here:](http://i.hizliresim.com/ZYg8vo.jpg).

It already work well. I don't think too about with ahuthentication. So why am i getting error when i change password remote user?  But it's interesting, isn't? 

I don't understand and I should change password.

**Comment by ademar** [comment]
> So why am i getting error when i change password remote user? 

I do not know, it shouldn't happen. Perhaps there is a special character in the new password that is messing with the XML parser; just speculating.

> But it's interesting, isn't? 

Yes, it is interesting. 

One way to find out is to pass `loggingEnabled = true` in the constructor of TcpTransport.

https://github.com/CodeMakerInc/EppLib.NET/blob/master/EppLib/TcpTransport.cs#L50

 Run a test and then post the contents of the file `easyepplog.txt`.

**Comment by rserit** [comment]
Old password has special character like **. New password including ..
I don't think about with special character. But i will try your solution.

**Comment by rserit** [comment]
My old password: 123**
My new password: 123..
I changed password and I'm working on localhost.
I don't change any line on project (like loggingEnabled = true). I changed remote user password again. When I work localhost, It is not getting error. It's work. But it fails in the real environment again.

There is an interesting situation. I noticed that after the error domain has been renewed. Remaing day was extended. By the way, domain isn't get on our datalist after error. 

> Summary:
> **When I don't change remote user password:** Domain can renew, domain can list on datalist, remaing day extend...
> When I change remote user password: Domain can't renew, it doesn't list on datalist...

How interesting...

**Comment by ademar** [comment]
@rserit did you had any progress in this issue ?

**Comment by regisrex** [comment]
> @ademar I fix it. The problem's about small application on server. There was an application. I learned later. It's a EPP app and provides connection. Server password also saved in application. When we change server password, application should know that :)

Mind explaining for me what's the solution @rserit ?

**Comment by rserit** [comment]
> > @ademar I fix it. The problem's about small application on server. There was an application. I learned later. It's a EPP app and provides connection. Server password also saved in application. When we change server password, application should know that :)
> 
> Mind explaining for me what's the solution @rserit ?

This error is a normal EPP error message returned to us from the registry EPP server. It is usually caused by incorrect data in the requests that we send. For example, if we renew for 11 years a domain, it will give this error due to the domain duration. We need to know your EPP request you sent. Could you share? @regisrex
