### ISSUE TITLE
EppLib still does not handle IIS cancel domain correctly

### ISSUE THREAD

**Issue by ManoManiac** [CodeMakerInc/EppLib.NET#27]
In fix #26 a workaround for clientDelete bug was implemented.
The problem also occurs when trying to get current info for a domain.

Example:

```
Dim getInfoDomainCmd As New IisDomainInfo(inDomain)
Dim iis_response As IisDomainInfoResponse
iis_response = iislocal.Execute(getInfoDomainCmd)
```

XML response: (excerpt)
```
<extension>
    <iis:infData xsi:schemaLocation="urn:se:iis:xml:epp:iis-1.2 iis-1.2.xsd" xmlns:iis="urn:se:iis:xml:epp:iis-1.2">
	<iis:state>active</iis:state>
	<iis:clientDelete>0</iis:clientDelete>
    </iis:infData>
</extension>
```

Error message:
`Failed to parse '0' as boolean value in iis:clientDelete`

Code in IisDomainInfoResponse.cs below.
clientDelete is handled as boolean and does not seem to be saved in any local variable:

```
// ClientDelete
node = children.SelectSingleNode("iis:clientDelete", namespaces);
if (node != null)
{
    bool value;
    if (!Boolean.TryParse(node.InnerText, out value))
    {
	throw new Exception(String.Format("Failed to parse '{0}' as boolean value in iis:clientDelete", node.InnerText));
    }
}
```

**Comment by ademar** [comment]
OK, I fixed this too.. Can you give it a try ? Thanks.

**Comment by ManoManiac** [comment]
Seems to work fine now. No error message. Really fast response! Thanks.
