### ISSUE TITLE
Cannot remove authInfo for domain name

### ISSUE THREAD

**Issue by ManoManiac** [CodeMakerInc/EppLib.NET#28]
Case scenario:  Domain name has an authInfo password, which is to be removed. This is not possible with EppLib.

According to RFC 5731 this shall be possible by using a <domain: null> element:
```
   -  A <domain:authInfo> element that contains authorization
      information associated with the domain object.  This mapping
      includes a password-based authentication mechanism, but the schema
      allows new mechanisms to be defined in new schemas.  A <domain:
      null> element can be used within the <domain:authInfo> element to
      remove authorization information.
```

**Comment by ademar** [comment]
@ManoManiac can you check if the last commit fixes this issue ?

To disable the password you would set DomainChange.NullAuthInfo = true

**Comment by ManoManiac** [comment]
Seems to be working! 👍
