### ISSUE TITLE
No connection could be made because the target machine actively refused it 

### ISSUE THREAD

**Issue by npsumesh** [CodeMakerInc/EppLib.NET#30]
Hi,
We are getting an error message "No connection could be made because the target machine actively refused it " in the server.
In locally, it is working fine.
How to solve this issue?

**Comment by ademar** [comment]
I think this is more of a networking issue than a library issue.  Can you share your connection code ?

**Comment by npsumesh** [comment]
Sorry, That is our Server issue,


Thanks
