### ISSUE TITLE
Service.Connect hangs in Windows Service

### ISSUE THREAD

**Issue by Sojaner** [CodeMakerInc/EppLib.NET#32]
This piece of code from `TcpTransport`
```C#
var lenghtBytes = new byte[4];
int read = 0;

while (read < 4)
{
      read = read + stream.Read(lenghtBytes, read, 4 - read);
}
```
works perfectly fine in a Console app, however it gets stuck in the loop and loops forever when ran in a Windows Service with Local System.

The reason for the never ending loops is that `stream.Read()` doesn't receive any bytes and `read` is always 0.

Does anyone have a any idea why it is, and how to fix it?

**Comment by ademar** [comment]
No idea, I use it from a Windows service without any issue.

Please reopen if it is still a problem.
