### ISSUE TITLE
The client and server cannot communicate, because they do not possess a common algorithm

### ISSUE THREAD

**Issue by npsumesh** [CodeMakerInc/EppLib.NET#33]
Hello Team,
We are getting an error message "The client and server cannot communicate, because they do not possess a common algorithm"  when connect with EPP.
How to solve this issue?

**Comment by ademar** [comment]
This is because mismatched TLS versions between the client and the server.
You can specify a TLS version on `Connect` like this.

```csharp 
var tcpTransport = new TcpTransport("epp.registry", 700, null, true);

var service = new Service(tcpTransport);

// SSL connection establishment
service.Connect(SslProtocols.Tls12);
```
