### ISSUE TITLE
Port to .NET Standard

### ISSUE THREAD

**Issue by foxxlpaul** [CodeMakerInc/EppLib.NET#39]
Hey guys, I want to use this package inside an ASP.NET Core project and this package might not be compatible.

Are there any plans to port this project to .NET Standard 2.0?

That way we can use this package inside for both: .NET Framework 4.6.1+ and .NET Core 2.0+
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by ademar** [comment]
I have started working on that, should be done soon.

**Comment by ademar** [comment]
@foxxlpaul  I've just published a new version 1.3.0 targeting netstandard2.0, give it a try.

**Comment by foxxlpaul** [comment]
@ademar Works like a charm!
