### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by db1996** [CodeMakerInc/EppLib.NET#41]
Hey guys, I'm trying to set up the connection but I can't get past `Services.Connect();`.
I'm using EppLib with a .net core application and I'm getting this exception:
`An unhandled exception occurred while processing the request.
NullReferenceException: Object reference not set to an instance of an object.
System.Net.Security.SecureChannel.EnsurePrivateKey(X509Certificate certificate)`

A couple lines down in the exception it says this:
`EppLib.TcpTransport.Connect(SslProtocols sslProtocols) in TcpTransport.cs`
                `77: stream.AuthenticateAsClient(EPP_REGISTRY_COM, clientCertificates, sslProtocols, false);`
`EppLib.Service.Connect(SslProtocols sslProtocols) in Service.cs`
            `39: transport.Connect(sslProtocols);`
`Backend.Controllers.HomeController.Index() in HomeController.cs`
            `23: service.Connect();`

Thanks in advance

**Comment by hognevevle** [comment]
What are you doing before `Services.Connect()`?

Here's what I'm using:

```
                var tcpTransport = new TcpTransport("host.tld", 700, null);
                var service = new Service(tcpTransport);
                service.Connect();
```

**Comment by db1996** [comment]
> What are you doing before `Services.Connect()`?
> 
> Here's what I'm using:
> 
> ```
>                 var tcpTransport = new TcpTransport("host.tld", 700, null);
>                 var service = new Service(tcpTransport);
>                 service.Connect();
> ```

Aah, you already fixed it, thanks!.

I had `var tcpTransport = new TcpTransport("testdrs.domain-registry.nl", 700, new X509Certificate(), true);`

Changing `new X509Certificate(),` to `null` did the trick
