### ISSUE TITLE
How do i use DNSSEC

### ISSUE THREAD

**Issue by db1996** [CodeMakerInc/EppLib.NET#42]
Hey guys, I just want to know how to use it, does anyone have an example code snippet?
It's not in the documentation and I don't see a constructor in the SecDNS classes.

Thanks in advance

**Comment by ademar** [comment]
You can see how it is used in the unit tests.

https://github.com/CodeMakerInc/EppLib.NET/blob/master/EppLib.UnitTests/SecDNSExtensionLocalTest.cs

**Comment by db1996** [comment]
> You can see how it is used in the unit tests.
> 
> https://github.com/CodeMakerInc/EppLib.NET/blob/master/EppLib.UnitTests/SecDNSExtensionLocalTest.cs

I can not figure out how to upload a new dnssec key. It keeps giving a response saying "Parameter valye policy error". 

the "Digest" value is supposed to be the public key right?

**Comment by ademar** [comment]
According to the RFC

"The digest is calculated by concatenating the canonical form of the
   fully qualified owner name of the DNSKEY RR with the DNSKEY RDATA,
   and then applying the digest algorithm.

     digest = digest_algorithm( DNSKEY owner name | DNSKEY RDATA);

      "|" denotes concatenation

     DNSKEY RDATA = Flags | Protocol | Algorithm | Public Key.

   The size of the digest may vary depending on the digest algorithm and
   DNSKEY RR size.  As of the time of this writing, the only defined
   digest algorithm is SHA-1, which produces a 20 octet digest."

**Comment by db1996** [comment]
Do you have an example with some data that works? Say i have a public key, algo, flags and protocol. How do i use that data to create a key?

I don't see any of that in the code, do i need to manually generate the keytag? Because I don't have that data

**Comment by ademar** [comment]
I think the keyTag is an arbitrary number. The only examples we have are the ones in the unit tests.
